version: '3.9'

networks:
  dev:
    driver: bridge

services:
  database:
    image: postgres:latest
    container_name: orders_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=orders_db
    restart: always
    volumes:
      - orders_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5
    networks:
      - dev

  api:
    build: .
    container_name: orders_api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ConnectionStrings__Default=Server=database;Database=orders_db;Username=postgres;Password=docker;Port=5432
    depends_on:
      database:
        condition: service_healthy
    networks:
      - dev

volumes:
  orders_data:
    name: "orders_data"