apiVersion: v1
kind: Pod
metadata:
  name: fast-food-orders-database
  labels:
    app: fast-food-orders-database
spec:
  volumes:
    - name: pgdata-storage
      persistentVolumeClaim:
        claimName: pgdata-pv-volume2
  containers:
    - name: fast-food-orders-database-container
      image: postgres:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 5432
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: pgdata-storage 
      envFrom:
        - secretRef:
            name: fast-food-orders-database-secret
