@API_HostAddress = http://localhost:5054/api

POST {{API_HostAddress}}/customers/
Content-Type: application/json

{
  "cpf": "90296682020",
  "name": "Leandro",
  "email": "leandro@gmail.com"
}
###

GET {{API_HostAddress}}/customers?Cpf=90296682020
Accept: application/json
###
