apiVersion: v1
kind: ConfigMap
metadata:
  name: fast-food-orders-api-configmap
  labels:
    app: fast-food-orders-api-configmap
data:
  ASPNETCORE_ENVIRONMENT: "#{ENVIRONMENT}#"
  ASPNETCORE_HTTP_PORTS: "8080"
