apiVersion: v1
kind: Service
metadata:
  name: fast-food-orders-api-service
spec:
  type: LoadBalancer
  selector:
    app: fast-food-orders-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
